### ISSUE TITLE
Trowbridge - Query

### ISSUE THREAD

**Issue by iainblackradley** [blackradley/nesscliffe#31]
I have begun entering the information for the data platform. When I got to the ‘refreshments’ and ‘special events’ headings the platform would not allow me to register ‘no’ in regards as to whether we had any. Please advise on this,

**Comment by iainblackradley** [comment]
Looks like she is typing on text not radio button, explains what she is seeing

**Comment by joejcollins** [comment]
We can change the behaviour to make it as expected.  Might take an hour.

**Comment by joejcollins** [comment]
Changed in a7feda509e6519269601512f044e289679402a32 and deployed.
