### ISSUE TITLE
Salford Community Leisure - Query

### ISSUE THREAD

**Issue by iainblackradley** [blackradley/nesscliffe#32]
I hope you’re well. My colleague and I are in the process of adding the information for our sites onto the Insight platform. I seem to be struggling though with inputting figures. Every time I try to save a number I keep getting a message to say it is not a valid amount. I’ve tried with no decimal places, inserting a comma after a thousand and various other things. If you could tell me where I’m going wrong I’d be very grateful.

**Comment by joejcollins** [comment]
I wonder if they are putting a £ sign in the field?

**Comment by PeteCollins** [comment]
They have been putting decimal places - advised to round up/down to nearest £. Do we need to consider allowing decimal places?

**Comment by joejcollins** [comment]
Allowing decimals is a good idea but there is no budget.  It would require changing the data type or adding something to do the rounding.  We already have an issue #30 logged to do this.  I suggest we leave it until we have budget.
