### ISSUE TITLE
Blists Hill: Confusion over multi-faceted sites. 

### ISSUE THREAD

**Issue by PeteCollins** [blackradley/nesscliffe#35]
Question: My name is ***** and I will be inserting the data for the Insight survey for the Ironbridge Gorge Museums. All looks fairly straightforward except for the fact that our sites are not, but I’m sure we will get around this! We will be reporting on Blists Hill Victorian Town which is a 52 acre open air site with over 60 separate accessible buildings and several catering outlets, the categories do not allow for varied answers, for example the ‘Distance to Refreshments’ category is difficult to convey as they are dotted around the site and I am presuming this means ‘distance from the entrance’?
 
One other question I would like to ask, and I do apologise if I am being slow - the small ‘i’ next to each category I presume means ‘put information in here’, and not ‘click for additional information’ regarding that category? #37 
 
Response:

For this study we are focusing on the primary means of retail/catering (we are hoping to extend this at a later date to include secondary sources of retail and catering), so in your case, I would suggest using the catering/retail areas that provide the biggest revenue, for example I would imagine that this would be either the cafe in the new entrance building, or the Forest Glen building. In terms of retail, I understand you have a variety of themed shops, yet in this case we would be looking for the information regarding the shop in the entrance/exit building. 

In terms of distance from entrance - this really varies site-to-site, but in your case I would suggest the distance from the front door of the entrance/exit building would be the best place. 

The small 'i' is an information point which provides some basic help text on each question - the information should be inputted in to the adjacent box.

**Comment by PeteCollins** [comment]
Their IT guy updated the version of IE to 11 and is now working fine. The problem was as follows:

"I was previously running on Internet Explorer 8. My operating system is Windows 7."

**Comment by joejcollins** [comment]
Were they OK with the response concerning multi faceted sites?  Can we close this issue?

**Comment by PeteCollins** [comment]
Yep - close it

On 10 April 2015 at 13:32, Joe J Collins <notifications@github.com> wrote:

> Were they OK with the response concerning multi faceted sites? Can we
> close this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blackradley/nesscliffe/issues/35#issuecomment-91537950>
> .
>



-- 
Peter Collins
Enterprise and Culture Executive
Black Radley Culture
e: peter_collins@blackradley.com
t: 0845 2260363
m: 07896799748
www.blackradley.com
LinkedIn <https://www.linkedin.com/in/utopianliving>
Twitter: @BlackRadley <https://twitter.com/BlackRadley>

*Improve resilience at your Museum, Gallery or Heritage site - find out
about Insight <http://insight.blackradley.com/>*

*Supported by the Digital R&D Fund for the Arts - Nesta, Arts & Humanities
Research Council and public funding by the National Lottery through Arts
Council England.*
