### ISSUE TITLE
Handel House Museum Error

### ISSUE THREAD

**Issue by PeteCollins** [blackradley/nesscliffe#36]
Dear Peter,
 
I hope you’re well. I was hoping to input the data today but I’m having trouble joining the survey. When I click to join it comes up with a page saying it is unavailable, with error code: ERR_SSL_VERSION_OR_CIPHER_MISMATCH.
 
Do let me know how I can get around this.

**Comment by PeteCollins** [comment]
Have requested the info of operating system/browser etc

**Comment by joejcollins** [comment]
Looks like a Chrome error (possibly on XP).  Could try FireFox browser (v19+) which has its own ECC SSL system? https://theadminzone.com/threads/cloudflare-universal-ssl-web-browser-compatibility.118718/

**Comment by PeteCollins** [comment]
1) I use the browser Google Chrome
2) All links lead to this error apart from the ‘What are the Details?’ which takes you to a page on Issuu
3) Our operating system is Microsoft Windows XP Professional
4) A screenshot of the error page – see below (have forwarded email to Joe).

**Comment by joejcollins** [comment]
Unfortunately we can't securely support Windows XP (it is no longer supported by Microsoft).  Options:

* Try Firefox rather than Chrome since it uses a different security system.
* We could set up an unsecured version of the interface.

**Comment by joejcollins** [comment]
I have set up an unsecured alias for the interface at http://unsecured.insight.blackradley.com/

There is a demonstration of it in action at https://saucelabs.com/tests/d347d8568ba34f9991c1d38bab90199d

**Comment by PeteCollins** [comment]
Have emailed to say use firefox or try a different PC that isn't XP. Will see what they say.

**Comment by joejcollins** [comment]
Did you get any response?

**Comment by PeteCollins** [comment]
Yes - got email saying sorted yesterday - haven't had chance to close yet.

On 16 April 2015 at 10:02, Joe J Collins <notifications@github.com> wrote:

> Did you get any response?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blackradley/nesscliffe/issues/36#issuecomment-93684321>
> .
>



-- 
Peter Collins
Enterprise and Culture Executive
Black Radley Culture
e: peter_collins@blackradley.com
t: 0845 2260363
m: 07896799748
www.blackradley.com
LinkedIn <https://www.linkedin.com/in/utopianliving>
Twitter: @BlackRadley <https://twitter.com/BlackRadley>

*Improve resilience at your Museum, Gallery or Heritage site - find out
about Insight <http://insight.blackradley.com/>*

*Supported by the Digital R&D Fund for the Arts - Nesta, Arts & Humanities
Research Council and public funding by the National Lottery through Arts
Council England.*
