### ISSUE TITLE
Retail Data Not Showing

### ISSUE THREAD

**Issue by PeteCollins** [blackradley/nesscliffe#43]
User is entering data, but doesn't appear on the readout.   This is for "Laing Gallery".

**Comment by joejcollins** [comment]
The retail spend per visitor is present in the earlier data.  See attached screen shot.

1. Perhaps the user is looking at the admissions graph?  There is no admission data.  The titles are above the graphs, but one might get confused.

2. Perhaps the visitor numbers has been removed from the data set.  The parameter is "retail spend per visitor". If there is no visitor numbers, the spend per visitor would be infinity, so nothing is shown.

![graphs](https://cloud.githubusercontent.com/assets/158219/9634260/bc33ccf0-5188-11e5-9c74-4c8827ce9270.JPG)

**Comment by joejcollins** [comment]
Confirmed that the retail income per visitor is present on the live data.  @PeteCollins Could you confirm that the user is finding the layout confusing?  If this is the case we'll add some separators or something.

**Comment by joejcollins** [comment]
Added horizontal lines to try and group the title with the graphs 9e7313fd21f5ec7392067df534fe1d63c57e0e43
